### ISSUE TITLE
怎么个运行顺序，需要安装些什么呢，下载了那个摘要数据集后

### ISSUE THREAD

**Issue by dajuzi123** [lipiji/TranSummar#1]

**Comment by lipiji** [comment]
参考：https://github.com/lipiji/neural-summ-cnndm-pytorch   另外我这个code还没有复现transformer该有的效果，还在调试，你如果发现bug，欢迎回复，谢谢。

**Comment by dajuzi123** [comment]
哦哦，谢谢，我再看看
