### ISSUE TITLE
Regarding paper

### ISSUE THREAD

**Issue by shreyapandit** [lipiji/TranSummar#10]
Hi there,

Thanks for sharing your work, I am so thankful for the detailed documentation and reproducibility of the code. It has been pretty straightforward to run it so far!

I wanted to read a bit more about your technique and was wondering if there is a corresponding paper you wrote/used as a reference for this implementation?

Thanks so much!

**Comment by lipiji** [comment]
Hi, this is the application of Transformer model with copy mechanism (https://arxiv.org/abs/1704.04368) and coverage tricks (https://arxiv.org/abs/1808.10792) for abstractive summarization.
