### ISSUE TITLE
您好，有试过跑中文数据的文本摘要生成吗，如果对数据进行处理呢？

### ISSUE THREAD

**Issue by BlueFishDream** [lipiji/TranSummar#11]

**Comment by lipiji** [comment]
中文原理一样的，分词或者单字形式，直接套上这套model就行了。

**Comment by BlueFishDream** [comment]
谢谢，已经弄明白了！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Piji&amp;nbsp;Li&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月13日(星期一) 上午9:00
收件人:&nbsp;&quot;lipiji/TranSummar&quot;<TranSummar@noreply.github.com&gt;;
抄送:&nbsp;&quot;BlueFishDream&quot;<975669552@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lipiji/TranSummar] 您好，有试过跑中文数据的文本摘要生成吗，如果对数据进行处理呢？ (#11)
