### ISSUE TITLE
如何使用copy和coverage

### ISSUE THREAD

**Issue by Sperao** [lipiji/TranSummar#18]
我想在我的模型使用copy和coverage，但是我对这两个机制的代码不熟悉，请问一下如何才能熟悉代码而加入到自己模型中，需要怎么去做比较快

**Comment by lipiji** [comment]
看pointer-generator的论文和代码

**Comment by Sperao** [comment]
> 看pointer-generator的论文和代码

代码看起来好复杂呀，有什么好的方法比较快看代码嘛

**Comment by Sperao** [comment]
> 看pointer-generator的论文和代码

有没有讲解这两个机制的代码
