### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 308.50 MiB (GPU 0; 10.92 GiB total capacity; 7.17 GiB already allocated; 275.50 MiB free; 247.76 MiB cached)

### ISSUE THREAD

**Issue by zhongxia96** [lipiji/TranSummar#3]
Hello, may I ask what is your GPU configuration? When I run it, there is always an error of insufficient memory, and it can only run if batch_size is adjusted to 8.

**Comment by lipiji** [comment]
Hi, I use a m40 gpu with 24g memory.
You can modify the configs according to your local conditions.
https://github.com/lipiji/TranSummar/blob/master/configs.py
