### ISSUE TITLE
Is model include transformer and pointer-generator

### ISSUE THREAD

**Issue by xiongma** [lipiji/TranSummar#8]
Hi, Can u tell me about this model more detail, Is this include transformer and pointer-generator? or just about transformer and copy net?

**Comment by xiongma** [comment]
@lipiji

**Comment by xiongma** [comment]
if your model is include pointer-generator, how to calculate gen in your model, can you tell me more detail about calculate gen in your model?

**Comment by lipiji** [comment]
This proj: transformer + copy + inference-stage coverage.
For the pointer-generator: https://github.com/lipiji/neural-summ-cnndm-pytorch

**Comment by xiongma** [comment]
Could u tell me more detail about how to calculate gen of pointer-generator in transformer? I saw you code, you implemented it.


Cally Ma (马雄)
Chongqing University of Post and Telecommunications
Mobile: +86 15025700935
E-mail: mx15025700935@aliyun.com




------------------------------------------------------------------
发件人：Piji Li <notifications@github.com>
发送时间：2019年6月3日(星期一) 14:21
收件人：lipiji/TranSummar <TranSummar@noreply.github.com>
抄　送：Cally <mx15025700935@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [lipiji/TranSummar] Is model include transformer and pointer-generator (#8)

This proj: transformer + copy + inference-stage coverage.
 For the pointer-generator: https://github.com/lipiji/neural-summ-cnndm-pytorch

**Comment by lipiji** [comment]
https://github.com/lipiji/TranSummar/blob/master/word_prob_layer.py#L46

**Comment by xiongma** [comment]
ok, I got u, thx


Cally Ma (马雄)
Chongqing University of Post and Telecommunications
Mobile: +86 15025700935
E-mail: mx15025700935@aliyun.com




------------------------------------------------------------------
发件人：Piji Li <notifications@github.com>
发送时间：2019年6月3日(星期一) 14:54
收件人：lipiji/TranSummar <TranSummar@noreply.github.com>
抄　送：Cally <mx15025700935@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [lipiji/TranSummar] Is model include transformer and pointer-generator (#8)

https://github.com/lipiji/TranSummar/blob/master/word_prob_layer.py#L46
